apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trend-app
  template:
    metadata:
      labels:
        app: trend-app
    spec:
      containers:
        - name: trend-app
          image: 242627333410.dkr.ecr.ap-southeast-2.amazonaws.com/trend-app:latest
          ports:
            - containerPort: 80